clone:
  depth: full
definitions:
  steps:
    - step: &push-to-github
        name: Push to Github
        script:
          - git push git@github.com:primeroIMS/primero-v2-migration.git master --tags
pipelines:
  branches:
    master:
      - step: *push-to-github
  tags:
    '*':
      - step: *push-to-github

